# Generated by Django 2.2.15 on 2020-08-29 01:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200828_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 29, 1, 18, 1, 83426, tzinfo=utc)),
        ),
    ]
